#!/usr/bin/env python3
"""Derive the systematic generator matrix G for the JS8 Normal (174,87) LDPC code.

The repo carries only the parity-check matrix H (as the k_check_var_j[87][7]
tables in gm/cuda/JS8LdpcCuda.cu).  OSD re-encodes from a most-reliable basis
and therefore needs a generator G (87 x 174) with G * H^T = 0.

Codeword layout (matches js8.cc:517): parity bits occupy c[0..86], the 87
message bits occupy c[87..173].  We build the systematic encoder G = [B | I_87]
so that c = m * G  =>  c[87:174] = m, with B = (H_p^-1 H_i)^T over GF(2).

Output: gm/cuda/JS8Generator.h  (static uint8_t g_js8_gen[87][174]).
"""
import re
import sys
import pathlib

N, M, K = 174, 87, 87
HERE = pathlib.Path(__file__).resolve().parent.parent
CU = HERE / "gm" / "cuda" / "JS8LdpcCuda.cu"
OUT = HERE / "gm" / "cuda" / "JS8Generator.h"


def parse_H(path):
    """Parse k_check_var_j[87][7] into a dense M x N GF(2) matrix (list of bytearrays)."""
    text = path.read_text()
    m = re.search(r"k_check_var_j\[87\]\[7\]\s*=\s*\{(.*?)\n\};", text, re.S)
    if not m:
        sys.exit("could not locate k_check_var_j table in " + str(path))
    body = m.group(1)
    H = [bytearray(N) for _ in range(M)]
    row = 0
    for line in body.splitlines():
        nums = re.findall(r"-?\d+", line.split("//")[0])
        if not nums:
            continue
        for v in (int(x) for x in nums):
            if v >= 0:
                H[row][v] ^= 1
        row += 1
    if row != M:
        sys.exit(f"parsed {row} checks, expected {M}")
    return H


# --- minimal GF(2) linear algebra on rows of bytearrays -------------------
def gf2_inverse(A):
    """Invert an n x n GF(2) matrix (rows of bytearrays). Returns None if singular."""
    n = len(A)
    M_ = [bytearray(A[i]) + bytearray(1 if j == i else 0 for j in range(n)) for i in range(n)]
    for col in range(n):
        piv = next((r for r in range(col, n) if M_[r][col]), None)
        if piv is None:
            return None
        M_[col], M_[piv] = M_[piv], M_[col]
        for r in range(n):
            if r != col and M_[r][col]:
                row_r, row_c = M_[r], M_[col]
                for c in range(2 * n):
                    row_r[c] ^= row_c[c]
    return [bytearray(M_[i][n:2 * n]) for i in range(n)]


def gf2_matmul(A, B):
    """A (a x b) * B (b x c) over GF(2)."""
    a, b, c = len(A), len(B), len(B[0])
    out = [bytearray(c) for _ in range(a)]
    for i in range(a):
        Ai, Oi = A[i], out[i]
        for k in range(b):
            if Ai[k]:
                Bk = B[k]
                for j in range(c):
                    Oi[j] ^= Bk[j]
    return out


def main():
    H = parse_H(CU)

    # Split H = [H_p | H_i], each 87 x 87.
    H_p = [bytearray(H[i][0:K]) for i in range(M)]
    H_i = [bytearray(H[i][K:N]) for i in range(M)]

    H_p_inv = gf2_inverse(H_p)
    if H_p_inv is None:
        sys.exit("H_p (parity columns) is singular over GF(2); column pivoting needed")

    B = gf2_matmul(H_p_inv, H_i)          # 87 x 87, B = H_p^-1 H_i ; encoder uses B^T
    Bt = [bytearray(B[r][c] for r in range(K)) for c in range(K)]  # transpose

    # G = [B^T | I_87]  (87 x 174)
    G = [bytearray(N) for _ in range(K)]
    for i in range(K):
        for j in range(K):
            G[i][j] = Bt[i][j]
        G[i][K + i] = 1

    # --- verify G * H^T = 0 over GF(2) ---
    Ht = [bytearray(H[r][c] for r in range(M)) for c in range(N)]  # N x M
    GHt = gf2_matmul(G, Ht)
    if any(any(row) for row in GHt):
        sys.exit("VERIFY FAILED: G * H^T != 0")

    # --- verify systematic: encode random messages, confirm c[87:]==m and parity ---
    import random
    random.seed(0)
    for _ in range(1000):
        m = bytearray(random.randint(0, 1) for _ in range(K))
        c = gf2_matmul([m], G)[0]
        if bytes(c[K:N]) != bytes(m):
            sys.exit("VERIFY FAILED: not systematic in info positions")
        # parity: H * c^T == 0
        for chk in range(M):
            acc = 0
            for col in range(N):
                if H[chk][col]:
                    acc ^= c[col]
            if acc:
                sys.exit("VERIFY FAILED: encoded codeword fails parity")

    write_header(G)
    print(f"OK: G * H^T = 0, systematic, 1000 random encodes pass -> {OUT}")


def write_header(G):
    lines = [
        "#pragma once",
        "#include <cstdint>",
        "",
        "// AUTO-GENERATED by tools/derive_js8_generator.py -- do not edit by hand.",
        "// Systematic generator for JS8 Normal (174,87) LDPC.  G * H^T = 0.",
        "// Codeword c = m * G ; c[0..86]=parity, c[87..173]=message (systematic).",
        "//",
        "// Verified: G*H^T==0 and 1000 random encodes satisfy H*c^T==0.",
        "",
        "static const uint8_t g_js8_gen[87][174] = {",
    ]
    for i, row in enumerate(G):
        bits = ",".join(str(b) for b in row)
        lines.append(f"    {{{bits}}}, // row {i}")
    lines.append("};")
    OUT.write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
